variables:
    Solution: src/DotNext.sln
    TestProject: src/DotNext.Tests/DotNext.Tests.csproj

jobs:
    - job: Windows
      pool:
        vmImage: windows-2019
        steps:
            - task: DotNetCoreCLI@1
              displayName: Test Debug
              inputs:
                command: test
                projects: $(TestProject)
                arguments: --configuration Debug
                nobuild: false
                testRunTitle: Debug